name: Moonraker Host Scanner

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Позволяет запускать вручную с сайта GitHub

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed main.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: dist/main.exe

  build-macos:
    name: Build on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed main.py

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: dist/main
